### ISSUE TITLE
[Feature] Allow using internal interface for all services

### ISSUE THREAD

**Issue by engel75** [openstack-exporter/openstack-exporter#172]
Currently even is `identity_interface: internal` is used the exporter will use the public endpoints to gather metrics. Could you please enable the exporter to honor `interface: internal`. Like:

```
clouds:
 'os1':
   region_name: "reg1"
   identity_api_version: 3
   identity_interface: internal
   interface: internal
   auth:
     username: "admin"
     password: "somesupersecret"
     project_name: "admin"
     project_domain_name: 'Default'
     user_domain_name: 'Default'
     auth_url: http://keystone.service.dev.i.exampe.org:5000/v3
     verify: false
```
