### ISSUE TITLE
error="Could not find cloud "

### ISSUE THREAD

**Issue by YEDEDD** [openstack-exporter/openstack-exporter#416]
openstack is installed by kolla. prometheus is not enabled by default.
After installing the prom_openstack_exporter, the error is reported as follows

```
[root@3D01 kolla]# curl http://10.0.xx.xx:9180/metrics
curl: (52) Empty reply from server
[root@3D01 kolla]# docker logs -f prom_openstack_exporter
ts=2024-10-28T06:27:10.758Z caller=main.go:68 level=error msg="openstack-exporter: error: required argument 'cloud' or flag --multi-cloud not provided, try --help"
ts=2024-10-28T06:27:10.758Z caller=main.go:71 level=info msg="Build context" build_context="(go=go1.22.8, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2024-10-28T06:27:10.758Z caller=main.go:160 level=info msg="openstack exporter started in legacy mode"
ts=2024-10-28T06:27:10.759Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9180
ts=2024-10-28T06:27:10.759Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9180
ts=2024-10-28T06:27:22.149Z caller=main.go:261 level=info msg="Starting openstack exporter version for cloud" version="(version=, branch=, revision=add5ae7c707ee08006720a7a2cd914638a7c3cee-modified)" cloud=
ts=2024-10-28T06:27:22.149Z caller=main.go:262 level=info msg="Build context" build_context="(go=go1.22.8, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2024-10-28T06:27:22.150Z caller=main.go:290 level=error err="enabling exporter for service failed" service=container-infra error="Could not find cloud "
ts=2024-10-28T06:27:22.150Z caller=main.go:290 level=error err="enabling exporter for service failed" service=database error="Could not find cloud "
ts=2024-10-28T06:27:22.150Z caller=main.go:290 level=error err="enabling exporter for service failed" service=image error="Could not find cloud "
ts=2024-10-28T06:27:22.151Z caller=main.go:290 level=error err="enabling exporter for service failed" service=gnocchi error="Could not find cloud "
ts=2024-10-28T06:27:22.151Z caller=main.go:290 level=error err="enabling exporter for service failed" service=orchestration error="Could not find cloud "
ts=2024-10-28T06:27:22.152Z caller=main.go:290 level=error err="enabling exporter for service failed" service=sharev2 error="Could not find cloud "
ts=2024-10-28T06:27:22.152Z caller=main.go:290 level=error err="enabling exporter for service failed" service=compute error="Could not find cloud "
ts=2024-10-28T06:27:22.152Z caller=main.go:290 level=error err="enabling exporter for service failed" service=identity error="Could not find cloud "
ts=2024-10-28T06:27:22.153Z caller=main.go:290 level=error err="enabling exporter for service failed" service=object-store error="Could not find cloud "
ts=2024-10-28T06:27:22.153Z caller=main.go:290 level=error err="enabling exporter for service failed" service=load-balancer error="Could not find cloud "
ts=2024-10-28T06:27:22.153Z caller=main.go:290 level=error err="enabling exporter for service failed" service=baremetal error="Could not find cloud "
ts=2024-10-28T06:27:22.154Z caller=main.go:290 level=error err="enabling exporter for service failed" service=placement error="Could not find cloud "
ts=2024-10-28T06:27:22.154Z caller=main.go:290 level=error err="enabling exporter for service failed" service=network error="Could not find cloud "
ts=2024-10-28T06:27:22.154Z caller=main.go:290 level=error err="enabling exporter for service failed" service=dns error="Could not find cloud "
ts=2024-10-28T06:27:22.155Z caller=main.go:290 level=error err="enabling exporter for service failed" service=volume error="Could not find cloud "
ts=2024-10-28T06:27:22.155Z caller=main.go:299 level=error err="No exporter has been enabled, exiting"
ts=2024-10-28T06:27:23.006Z caller=main.go:68 level=error msg="openstack-exporter: error: required argument 'cloud' or flag --multi-cloud not provided, try --help"
ts=2024-10-28T06:27:23.006Z caller=main.go:71 level=info msg="Build context" build_context="(go=go1.22.8, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2024-10-28T06:27:23.006Z caller=main.go:160 level=info msg="openstack exporter started in legacy mode"
```
The compose documents are as follows:
```
[root@3D01 prome-openstack-export]# cat docker-compose.yaml
version: '3.8'

services:
  prom_openstack_exporter:
    image: ghcr.io/openstack-exporter/openstack-exporter:latest
    container_name: prom_openstack_exporter
    ports:
      - "9180:9180"
    volumes:
      - ./clouds.yaml:/etc/openstack/clouds.yaml
    restart: unless-stopped
    privileged: true
```

Excuse me, what is the problem?

**Comment by Sharpz7** [comment]
Hey @YEDEDD,

I think by default the docker image expects a different format for querying the API.

From the README:

## Multi cloud mode

```bash
./openstack-exporter --os-client-config /etc/openstack/clouds.yaml --multi-cloud
curl "http://localhost:9180/probe?cloud=region.mycludprovider.org"
```
## Legacy mode

```bash
./openstack-exporter --os-client-config /etc/openstack/clouds.yaml myregion.cloud.org
curl "http://localhost:9180/metrics" +
```

I think the docker image uses multi-cloud mode by default. If you edit your docker compose to edit the image command, that should fix your issue:

(Note this has not been tested, so take it as a guide)
```yaml
version: '3.8'

services:
  prom_openstack_exporter:
    image: ghcr.io/openstack-exporter/openstack-exporter:latest
    container_name: prom_openstack_exporter
    ports:
      - "9180:9180"
    volumes:
      - ./clouds.yaml:/etc/openstack/clouds.yaml
    restart: unless-stopped
    privileged: true
    command: ["/bin/openstack-exporter", "YOUR_CLOUD_HERE"]
```

I will also note that OS-Exporter supports installation from Kola Ansible directly, I have never used it before but just incase you missed it, as I think this is an option for you?

- By using [kolla-ansible](https://github.com/openstack/kolla-ansible) by setting enable_prometheus_openstack_exporter: true
