### ISSUE TITLE
After restarting openstack controller + openstack exporter no services in metrics

### ISSUE THREAD

**Issue by cognoz** [openstack-exporter/openstack-exporter#44]
Version: 0.6.0
Environment: 1 controller node with collocated openstack-exporter service (systemd unit, After=network.targert)

Description: After rebooting controller node with collocated openstack-exporter service, fetching metrics doesn't work any more, error:
**level=error msg="enabling exporter for service network failed: The service is currently unable to handle the request  due to a temporary overloading or maintenance. This is a temporary condition. Try again later." source="main.go:51"
level=info msg="Starting HTTP server on :9183" source="main.go:72"**
After restarting openstack-exporter service everything starts working
```yaml
clouds.yaml:
clouds:
  RegionOne:
   region_name: "RegionOne"
   identity_api_version: 3
   identity_interface: internal
   auth:
     username: admin
     password: 'pass'
     project_name: admin
     project_domain_name: Default
     user_domain_name: Default
     auth_url: http://ip:5000/v3
   verify: False
```

Other info: If openstack exporter is not collocated with rebooted controller, exporter continues polling and everything works, so mb something in OS was not ready, then exporter started

**Comment by niedbalski** [comment]
Hey @cognoz 

* Can you let me know how can I reproduce this issue?

**Comment by cognoz** [comment]
Hey @niedbalski 
Basically, you'll need openstack environment (even AIO should work), 
and working openstack exporter as systemd unit on one of controllers(infra nodes). 
here is my example systemd unit for openstack exporter:
```bash
[Unit]
Description=prometheus-openstack-exporter
After=network.target

[Service]
SyslogIdentifier=prometheus_openstack_exporter
ExecStart=/usr/local/bin/openstack_exporter --web.listen-address=:9000 --os-client-config=/etc/prometheus-openstack-exporter/clouds.yaml RegionOne
KillMode=process

[Install]
WantedBy=multi-user.target
```

and here example clouds.yaml
```yaml
clouds:
  RegionOne:
   region_name: RegionOne
   identity_api_version: 3
   identity_interface: internal
   auth:
     username: admin
     password: admin
     project_name: admin
     project_domain_name: Default
     user_domain_name: Default
     auth_url: http:ip:5000/v3 
   verify: False
```
So, copy exporter to /usr/local/bin on controller, chmod +x on it, create clouds.yaml? create systmed unit, enable and start unit. After that, reboot this contoller. 
All my exporters (configured similliary with systemd) on controllers work fine after reboot (rabbitmq, mysql, node, etc..). but not openstack exporter.
