### ISSUE TITLE
Add version option

### ISSUE THREAD

**Issue by vooon** [openstack-exporter/openstack-exporter#70]
Hello,

I noticed, that exporter do not have `--version` option.
But since you already uses `promu` and prometheus common, that should be relatively easy to get.

Firstly please modify `.promu.yaml` as follows:
```yaml
go:
  version: 1.13

repository:
  path: github.com/openstack-exporter/openstack-exporter

build:
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
  files:
    - LICENSE

crossbuild:
  platforms:
    - linux/amd64
    - linux/arm64
```

NOTE: I removed flags `-mod vendor` because i prefer to use modules cache instead of `vendor/`.

And secondly: add `--version` option to use `common.version.Print()`.
